version: '3.7'
services:
  app:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    ports:
      - 25565:25565
    volumes:
      - ./minecraft-dat:/data
